- name: Configure instance(s)
  hosts: jenkins_test
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    ansible_ssh_private_key_file: /var/lib/jenkins/continuous-integration.pem
  vars_files:
    # overrides specific to the jenkins test playbook
    - "{{ secure_dir }}/vars/edx_jenkins_tests.yml"
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
    - xqueue
    - xserver
    - ora
    - rabbitmq
